linters-settings:
  golint:
    min-confidence: 0.3
  goimports:
    local-prefixes: github.com

linters:
  enable:
    - deadcode
    - errcheck
    - exportloopref
    - gocritic
    - gocyclo
    - goimports
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - nakedret
    - revive
    - staticcheck
    - structcheck
    - unused
    - varcheck
  disable-all: true

run:
  timeout: 10m
