name: CI

on:
  push:
    branches:
    - '**'
    paths-ignore:
    - '**.md'
    tags-ignore:
    - 'v*' # Don't run CI tests on release tags

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        git submodule update --init --recursive go.mk
        PATH=$(go env GOPATH)/bin:$PATH make lint test-verbose
