name: CI

on:
  push:
    branches:
    - '**'
    paths-ignore:
    - '**.md'
    tags-ignore:
    - 'v*' # Don't run CI tests on release tags

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive go.mk
      - uses: ./go.mk/.github/actions/setup

      - uses: ./go.mk/.github/actions/pre-check

      - run: make test-verbose
  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash
      - name: Run govulncheck
        run: govulncheck ./...
        shell: bash
